[#issues]
= ℹ️ Issues

(TODO: move these to GitHub issues.
This was a valiant effort at avoiding vendor lock-in)

Here's a quick summary of the stuff I'm aware of and working on.
IDs start with `am` to avoid conflicts with IDs that might be generated by some other issue tracker, should I choose one.

[cols="1,3,1,2"]
|===
|id |description |status | details

|am55 |improve htmlproofer |OPEN |<<am55_detail,see below>>
|am59 |port `book/build.sh` to Windows |OPEN |
|am61 |port `mario/ansible/provision.sh` to Windows |OPEN |
|am62 |improve render of titled sidebars in macOS Books |OPEN |title box overlaps sidebar box in Books 3.1 with Gray and Night themes
|am63 |add auto-hyphenation |OPEN |<<am63_detail,see below>>
|am64 |add _Cross references_ to print PDF |OPEN |<<am64_detail,see below>>
|am65 |fix sidebar deep links in EPUB |OPEN |see https://github.com/asciidoctor/asciidoctor-epub3/pull/480[this patch]
|am66 |improve Kindle compatibility |OPEN |<<am66_detail,see below>>
|am67 |improve book build: robust, secure |OPEN |<<am67_detail,see below>>, also see am59
|===

[#am55_detail]
== ℹ️ am55: improve htmlproofer

`book/.internal-build.sh` runs `htmlproofer`, which returns some spurious failures.
Currently I ignore these failures with an `|| true` statement.
It would be better to sqelch or fix them.
This is possible by instrumenting links in the text or adjusting the way htmlproofer is configured and run.

Some recent output:

....
Running 3 checks (Images, Links, Scripts) in steadfast.html on *.html files ...


Checking 173 external links
Checking 94 internal links
Checking internal link hashes in 1 file
Ran on 1 file!


For the Links check, the following failures were found:

* At steadfast.html:6581:

  http://catb.org/jargon/html/G/Good-Thing.html is not an HTTPS link

For the Links > External check, the following failures were found:

* At steadfast.html:5354:

  External link https://github.com/wallabag/docker#upgrading failed: https://github.com/wallabag/docker exists, but the hash 'upgrading' does not (status code 200)

* At steadfast.html:5713:

  External link https://matrix.to/#/#selfhosted:matrix.org failed: https://matrix.to/ exists, but the hash '/#selfhosted:matrix.org' does not (status code 200)

* At steadfast.html:5988:

  External link https://github.com/strukturag/nextcloud-spreed-signaling#running-with-docker failed: https://github.com/strukturag/nextcloud-spreed-signaling exists, but the hash 'running-with-docker' does not (status code 200)


HTML-Proofer found 4 failures!
....

[#am63_detail]
== ℹ️ am63: add auto-hyphenation

I want full justification in the printed book, and I want words reasonably hyphenated.
Asciidoctor-PDF can do this!
Just add the `text-hyphen` gem and enable it in the theme.
https://github.com/meonkeys/print-this/commit/91e31471fdb848c2ff8ab8f2fc31c5adcfa0c2b8[Here's an example].

Unfortunately for me, [.line-through]#URLs and# inline code spans are also hyphenated.

See https://asciidoctor.zulipchat.com/#narrow/stream/288690-users.2Fasciidoctor-pdf/topic/.E2.9C.94.20In-line.20hyphen.20overrides.20for.20.22Special.22.20text.3F[this chat thread] and https://github.com/asciidoctor/asciidoctor-pdf/pull/2513[this patch] (merged on May 26, 2024).

[#am64_detail]
== ℹ️ am64: add _Cross references_ to print PDF

Ideally I'd like a full set of lists of cross-referenced blocks of significant/titled content like figures, tables, sidebars, and listings (code snippets) in the _Cross references_ chapter.
This currently relies on the https://rubygems.org/gems/asciidoctor-lists[asciidoctor-lists] extension.

The print PDF omits the entire _Cross references_ chapter because page numbers are not rendered.
See: https://github.com/Alwinator/asciidoctor-lists/issues/14

Links in EPUB output break for anything without an explicit ID--something about the UUIDs auto-generated by asciidoctor-lists confuses the EPUB3 backend.
Otherwise I'd only need explicit IDs for special cases.
See: https://github.com/Alwinator/asciidoctor-lists/issues/25

[#am66_detail]
== ℹ️ am66: improve Kindle compatibility

The EPUB loads on Kindle devices, but there are a few issues:

* cross-references to sidebars are dead links (not clickable / touchable)
* emoji don't appear
* definition list terms (e.g. Glossary) are italic instead of bold
* figure captions aren't centered

I don't use Kindle apps or devices; I've only seen these via the Kindle Previewer.

Perhaps related, KDP says a KPF created from Kindle Previewer https://github.com/asciidoctor/asciidoctor-epub3/issues/481[contains only images, is not reflowable, and fixed format is required].

https://asciidoctor.zulipchat.com/#narrow/stream/346540-users.2Fasciidoctor-epub3/[Discussion about same].

See "EPUB" → "Kindle" in `Readme.adoc` for all book format quality rankings.

[#am67_detail]
== ℹ️ am67: more resilient, secure book build

`sudo book/build.sh` fails on Linux at `addgroup` failure - The group `root` already exists.
This is documented in `book/Readme.md` but is still annoying and unnecessary.

Even as non-root, building the books appears to fail on Ubuntu 22.04 LTS unless the `docker-buildx` package is installed.

The main thing making `book/build.sh` brittle is that it's trying to be more secure by matching the non-root host user with an in-container non-root user.
Does this appreciably help security?
I don't know.
If it doesn't, we should just collapse `book/.Dockerfile` and `book/.Dockerfile.insecure`, use `root`, and simplify `book/build.sh`.

We should also explore/recommend https://docs.docker.com/engine/security/rootless/[rootless Docker] and https://docs.docker.com/engine/security/userns-remap/[user namespaces] when we seek to improve `book/build.sh`.
