= 📖 Steadfast Self-Hosting
:hide-uri-scheme:

This is the source code for a most excellent book about self-hosting.

_Steadfast_ primarily targets aspiring self-hosters looking for a quick and reliable method to get started.

Please https://selfhostbook.com/buy/[buy] or <<how_to_build,build>> a <<book_formats,nicely-formatted copy>> of the book for your reading pleasure.
You may also https://selfhostbook.com/donate/[donate] to support my efforts.

== 📂 Directory structure

[cols="1,2"]
|===
|path |description

|`book/` |sources for the book
|`mario/` |sources for mario provisioning tool
|`pelican/` |sources for https://selfhostbook.com
|===

[#book_formats]
== 🖨️ Book formats

|===
|version |device |quality |index |_Cross references_ chapter

|EPUB |calibre e-book viewer |good 🙂 |No |Yes
|EPUB |Kobo e-reader |ok 😐 |No |Yes
|EPUB |FBReader |bad ☹️ |No |Yes
|EPUB |macOS Books |good 🙂 |No |Yes
|EPUB |Kindle |ok 😐 |No |Yes
|HTML |Firefox web browser |good 🙂 |No |Yes
|raw Asciidoc |https://docs.asciidoctor.org/browser-extension/[web browser] |good 🙂 |No |No
|screen PDF |Firefox web browser |good 🙂 |Yes |Yes
|screen PDF |evince PDF viewer |good 🙂 |Yes |Yes
|print PDF |evince PDF viewer |good 🙂 |Yes |No
|print PDF |Firefox web browser |good 🙂 |Yes |No
|standard quality paperback |ink & paper |good 🙂 |Yes |No
|premium quality paperback |ink & paper |TBD, hoping for: great 😍🥹🤩 |Yes |No
|===

The index is a section in the back of the book with references to select notable occurrences of terms and their page numbers.
Asciidoctor https://docs.asciidoctor.org/asciidoc/latest/sections/user-index/[only generates an index for PDF output].
I think that's OK since the other book formats are searchable.

The print PDF excludes _Cross references_ because <<am64_detail,page numbers are not rendered>>, reducing the usefulness of this chapter in print.

[#how_to_build]
== 🏗️ How to build the book

Run `./book/build.sh` to generate your own typeset outputs.
See `book/Readme.md` for details.

This build should be ported to more operating systems.
See <<issues,am59>>, above.

== 🪡 Patches welcome

Your contributions are most welcome!
When submitting a patch, please:

. Heed the link:style-guide.adoc[style guide].
. Sign off every commit (`git commit --signoff`).
Sorry, I know this is annoying, but it is important.
It certifies you wrote or otherwise have the right to submit the patch, following https://developercertificate.org[Developer Certificate of Origin, version 1.1].

== 📜 Warranty

None.

== 📜 Copyright and license

* the book: see copyright and license info in `book/steadfast.asciidoc`
* mario: see `mario/Readme.md`

== 🗨️ Feedback

Please https://selfhostbook.com/contact/[send me feedback]!
Originally shared with early reviewers; left here since I want to continue to iterate and improve in areas covered by these questions.

* What are your first impressions? Cover, title, table of contents, font, style, page size, book length, etc.
* Any/all factual, spelling, grammatical, and structural errors.
* Overall manuscript critique, comprehensive or line edits, copy-editing, proofreading.
* Does it make sense what I'm trying to convey and how?
* Consistency of voice, level of detail, narrative flow.
* Anywhere a diagram or photo would significantly help to illustrate a point.
* Any sections that should be rewritten, rethought, or removed.
* Is there a relevant and useful technology that isn't mentioned and should be?
* Test out mario on your own hardware/VM. Does it work for you as advertised?
* Is this book, this code, these ideas something you actually, personally want/read/use?
* Is this something you'd recommend to others?
* What would you expect to pay for a print copy?
* What would you expect to pay for a digital copy?
* Any feedback on the https://selfhostbook.com[book website] and this readme?

[#issues]
== ℹ️ Issues

Here's a quick summary of the stuff I'm aware of and working on.
IDs start with `am` to avoid conflicts with IDs that might be generated by some other issue tracker, should I choose one.

[cols="1,3,1,2"]
|===
|id |description |status | details

|am39 |test all links and references in all output formats |OPEN |
|am43 |port to future home (re-do this Readme) |OPEN |
|am44 |re-test mario start to finish |OPEN |
|am46 |make _Services_ map 1:1 with mario: add dyndns, mail, Traefik |OPEN |
|am48 |use service nicknames consistently: e.g. `media.example.com` |OPEN |
|am49 |improve FOSS "`profit`" argument |OPEN |
|am55 |improve htmlproofer |OPEN |<<am55_detail,see below>>
|am57 |professional editing: focus on structure & style |IN PROGRESS |tech review!
|am59 |port `book/build.sh` to Windows |OPEN |
|am61 |port `mario/ansible/provision.sh` to Windows |OPEN |
|am62 |improve render of titled sidebars in macOS Books |OPEN |title box overlaps sidebar box in Books 3.1 with Gray and Night themes
|am63 |add auto-hyphenation |OPEN |<<am63_detail,see below>>
|am64 |add _Cross references_ to print PDF |OPEN |<<am64_detail,see below>>
|am65 |fix sidebar deep links in EPUB |OPEN |see https://github.com/asciidoctor/asciidoctor-epub3/pull/480[this patch]
|am66 |improve Kindle compatibility |OPEN |<<am66_detail,see below>>
|===

[#am55_detail]
== ℹ️ am55: improve htmlproofer

`book/.internal-build.sh` runs `htmlproofer`, which returns some spurious failures.
Currently I ignore these failures with an `|| true` statement.
It would be better to sqelch or fix them.
This is possible by instrumenting links in the text or adjusting the way htmlproofer is configured and run.

Some recent output:

....
Running 3 checks (Images, Links, Scripts) in steadfast.html on *.html files ...


Checking 173 external links
Checking 94 internal links
Checking internal link hashes in 1 file
Ran on 1 file!


For the Links check, the following failures were found:

* At steadfast.html:6581:

  http://catb.org/jargon/html/G/Good-Thing.html is not an HTTPS link

For the Links > External check, the following failures were found:

* At steadfast.html:5354:

  External link https://github.com/wallabag/docker#upgrading failed: https://github.com/wallabag/docker exists, but the hash 'upgrading' does not (status code 200)

* At steadfast.html:5713:

  External link https://matrix.to/#/#selfhosted:matrix.org failed: https://matrix.to/ exists, but the hash '/#selfhosted:matrix.org' does not (status code 200)

* At steadfast.html:5988:

  External link https://github.com/strukturag/nextcloud-spreed-signaling#running-with-docker failed: https://github.com/strukturag/nextcloud-spreed-signaling exists, but the hash 'running-with-docker' does not (status code 200)


HTML-Proofer found 4 failures!
....

[#am63_detail]
== ℹ️ am63: add auto-hyphenation

I want full justification in the printed book, and I want words reasonably hyphenated.
Asciidoctor-PDF can do this!
Just add the `text-hyphen` gem and enable it in the theme.
https://github.com/meonkeys/print-this/commit/91e31471fdb848c2ff8ab8f2fc31c5adcfa0c2b8[Here's an example].

Unfortunately for me, [.line-through]#URLs and# inline code spans are also hyphenated.

See https://asciidoctor.zulipchat.com/#narrow/stream/288690-users.2Fasciidoctor-pdf/topic/.E2.9C.94.20In-line.20hyphen.20overrides.20for.20.22Special.22.20text.3F[this chat thread] and https://github.com/asciidoctor/asciidoctor-pdf/pull/2513[this patch] (merged on May 26, 2024).

[#am64_detail]
== ℹ️ am64: add _Cross references_ to print PDF

Ideally I'd like a full set of lists of cross-referenced blocks of significant/titled content like figures, tables, sidebars, and listings (code snippets) in the _Cross references_ chapter.
This currently relies on the https://rubygems.org/gems/asciidoctor-lists[asciidoctor-lists] extension.

The print PDF omits the entire _Cross references_ chapter because page numbers are not rendered.
See: https://github.com/Alwinator/asciidoctor-lists/issues/14

Links in EPUB output break for anything without an explicit ID--something about the UUIDs auto-generated by asciidoctor-lists confuses the EPUB3 backend.
Otherwise I'd only need explicit IDs for special cases.
See: https://github.com/Alwinator/asciidoctor-lists/issues/25

[#am66_detail]
== ℹ️ am66: improve Kindle compatibility

The EPUB loads on Kindle devices, but there are a few issues leading to the current quality ranking:

* smooshed SVG: _WAN into LAN traffic flow diagram_
* cross-references to sidebars are dead links (not clickable / touchable)
* no text visible in _Pi-hole DNS traffic flow diagram_

I don't use Kindle apps or devices; I've only seen these via the Kindle Previewer.

Perhaps related, KDP says a KPF created from Kindle Previewer https://github.com/asciidoctor/asciidoctor-epub3/issues/481[contains only images, is not reflowable, and fixed format is required].

https://asciidoctor.zulipchat.com/#narrow/stream/346540-users.2Fasciidoctor-epub3/[Discussion about same].
