version: '3.5'

services:
  app:
    image: nextcloud:stable
    environment:
      MYSQL_HOST: db:3306
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: redispassword
      OVERWRITEPROTOCOL: https
      TRUSTED_PROXIES: traefik-reverse-proxy-1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nc-https.entrypoints=websecure"
      - "traefik.http.routers.nc-https.rule=Host(`cloud.{{ lookup('env', 'MARIO_DOMAIN_NAME') }}`)"
      - "traefik.http.routers.nc-https.tls.certresolver=myresolver"
      - "traefik.http.routers.nc-https.middlewares=nc-head,nc-redir,lan-only"
      - "traefik.http.middlewares.nc-head.headers.stsSeconds=155520011"
      - "traefik.http.middlewares.nc-head.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nc-head.headers.stsPreload=true"
      # These are required for groupware (calendar, contacts, tasks)
      - "traefik.http.middlewares.nc-redir.redirectregex.regex=/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc-redir.redirectregex.replacement=/remote.php/dav/"
    volumes:
      - /data/nextcloud/root:/var/www/html:rw
      - /data/shared/media/video:/data/video:rw
      - /data/shared/media/music:/data/music:rw
    networks:
      - nextcloud
      - traefik_default
    restart: unless-stopped
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: mysqlnextcloudrootpassword
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --skip-innodb-read-only-compressed
    networks:
      - nextcloud
    restart: unless-stopped
    volumes:
      - /data/nextcloud/db:/var/lib/mysql
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --requirepass redispassword
    networks:
      - nextcloud
networks:
  nextcloud:
    name: nextcloud
  traefik_default:
    external: true
