version: '3'

services:
  # Amazon Route 53 dynamic DNS client
  client:
    image: bshaw/route53-dyndns
    environment:
      AWS_ACCESS_KEY_ID: "{{ lookup('env', 'DNS_API_KEY') }}"
      AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'DNS_API_SECRET') }}"
      ROUTE53_DOMAIN_A_RECORD: "*.{{ lookup('env', 'MARIO_DOMAIN_NAME') }}"
      ROUTE53_UPDATE_FREQUENCY: "3000"
    restart: unless-stopped
