<style type="text/css">
  h1 {
    border-bottom: 1px solid #ddd;
  }
  body {
    font-family: sans-serif;
    /* background: black; */ /* FIXME - temp dark mode */
    /* color: white; */ /* FIXME - temp dark mode */
	max-width: 45em;
  }
  td, th {
    border: 1px solid black;
    padding: 5px;
  }
  tr.odd {
    background-color: lightgray;
  }
  table {
    border-collapse: collapse;
  }
  li > p {
    margin-top: 0px;
    margin-bottom: 0px;
  }
  .todo {
    background-color: yellow;
  }
  code {
    background-color: #f8f8f8;
  }
  /* use gray background for the entire rectangle containing a non-syntax-highlightable block of text as it would appear in a terminal */
  div.terminalText {
    background-color: #f8f8f8;
  }
</style>
