---
- name: Install packages
  apt:
    name:
      - docker.io
      - docker-compose-v2
    state: present

- name: Enable service
  service:
    name: docker.service
    state: started
    enabled: yes
