---
- name: Install packages
  apt:
    name:
      - docker.io
      # kept only for /usr/share/bash-completion/completions/docker-compose
      - docker-compose
      - docker-compose-v2
    state: present

- name: Enable service
  service:
    name: docker.service
    state: started
    enabled: yes
