version: '3.5'

services:
  app:
    image: wallabag/wallabag
    # wallabag's root/entrypoint.sh drops privileges
    user: root:root
    depends_on:
      - valkey
    environment:
      # detailed documentation at https://github.com/wallabag/docker#environment-variables
      # remove MYSQL_ROOT_PASSWORD after first startup, or you'll see this in the logs:
      # "WARN: MySQL database is already configured. Remove the environment variable with root password."
      SYMFONY__ENV__REDIS_HOST: valkey
      SYMFONY__ENV__REDIS_PASSWORD: redispassword
      SYMFONY__ENV__TWOFACTOR_AUTH: 'true'
      SYMFONY__ENV__FOSUSER_REGISTRATION: 'true'
      SYMFONY__ENV__FOSUSER_CONFIRMATION: 'true'
      SYMFONY__ENV__DOMAIN_NAME: "https://wallabag.{{ lookup('env', 'MARIO_DOMAIN_NAME') }}"
      SYMFONY__ENV__SERVER_NAME: "{{ lookup('env', 'MARIO_DOMAIN_NAME') }}"
    volumes:
      - /data/wallabag/main:/var/www/wallabag/data
      - /data/wallabag/images:/var/www/wallabag/web/assets/images
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wallabag-https.entrypoints=websecure"
      - "traefik.http.routers.wallabag-https.rule=Host(`wallabag.{{ lookup('env', 'MARIO_DOMAIN_NAME') }}`)"
      - "traefik.http.routers.wallabag-https.tls.certresolver=myresolver"
      - "traefik.http.routers.wallabag-https.middlewares=lan-only"
    networks:
      - wallabag
      - traefik_default
    restart: unless-stopped
  valkey:
    image: valkey/valkey
    user: {{ wallabag_user }}:{{ wallabag_group }}
    restart: unless-stopped
    command: valkey-server --requirepass redispassword
    networks:
      - wallabag
networks:
  wallabag:
    name: wallabag
  traefik_default:
    external: true
