source 'https://rubygems.org'

gem 'asciidoctor', '2.0.20'

gem 'asciidoctor-epub3', '2.1.0'
gem 'asciidoctor-pdf', '2.3.12'

gem 'pygments.rb', '2.4.1'
gem 'epubcheck-ruby', '5.1.0.0'
gem 'html-proofer', '5.0.8'
