source 'https://rubygems.org'

gem 'rake', '13.1.0'
gem 'asciidoctor', '2.0.20'

gem 'asciidoctor-fb2', '0.7.0'
gem 'asciidoctor-epub3', :github => 'asciidoctor/asciidoctor-epub3', :ref => 'dffd2a427207ff9bcb105adb1981f27b54fe4d63'
gem 'asciidoctor-pdf', '2.3.10'

gem 'pygments.rb', '2.4.1'
gem 'epubcheck-ruby', '5.1.0.0'
gem 'html-proofer', '5.0.8'
gem 'kindlegen', '3.1.1'
