steadfast.print.pdf: steadfast.asciidoc
	./build.sh printPdf
steadfast.epub: steadfast.asciidoc
	./build.sh epub
steadfast.html: steadfast.asciidoc
	./build.sh html
steadfast.screen.pdf: steadfast.asciidoc
	./build.sh screenPdf
